packaging_format = 2

id = "minio"
name = "MinIO server"
description.en = "High Performance, Kubernetes Native Object Storage"
description.fr = "Serveur de stockage d'objets hautes performances"

version = "2023.09.07~ynh2"

maintainers = ["Raoul de Limezy"]

[upstream]
license = "AGPL-3.0-only"
website = "https://min.io"
admindoc = "https://docs.min.io/"
code = "https://github.com/minio/minio"
cpe = "cpe:2.3:a:minio:minio"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "150M"
ram.build = "700M"
ram.runtime = "700M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources]
        [resources.sources.minio]
        extract = false
        in_subdir = false

        arm64.url = "https://dl.min.io/server/minio/release/linux-arm64/archive/minio.RELEASE.2023-09-07T02-05-02Z"
        arm64.sha256 = "b32d3ab56d2184220b3a0cb7d82fd5f8659f61230f6d8047a8ce09ed1d20e291"

        amd64.url = "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2023-09-07T02-05-02Z"
        amd64.sha256 = "d6c6a13c25b91893ffcd8fc4a2bdb4f0653352705cbf38fcb3eadbe7dec93e0f"

        [resources.sources.mc]
        extract = false
        in_subdir = false

        arm64.url = "https://dl.min.io/client/mc/release/linux-arm64/archive/mc.RELEASE.2023-09-07T22-48-55Z"
        arm64.sha256 = "6af5567ae0cc2195a524d62655344dfdcdc677a6457f192cca7752e389898403"

        amd64.url = "https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2023-09-07T22-48-55Z"
        amd64.sha256 = "e3beda5f8c7622eb263a0218d07fb0dabc11c121d1d8a086c6f110b905faf351"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    main.default = 9000
    console.default = 36669
