packaging_format = 2

id = "minio"
name = "MinIO"
description.en = "High Performance, Kubernetes Native Object Storage"
description.fr = "Serveur de stockage d'objets hautes performances"

version = "2025.07~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://min.io"
admindoc = "https://docs.min.io/"
code = "https://github.com/minio/minio"
cpe = "cpe:2.3:a:minio:minio"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "150M"
ram.build = "700M"
ram.runtime = "700M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources]

        [resources.sources.minio]
        extract = false
        in_subdir = false
        amd64.url = "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2025-07-23T15-54-02Z"
        amd64.sha256 = "eef6581f6509f43ece007a6f2eb4c5e3ce41498c8956e919a7ac7b4b170fa431"
        arm64.url = "https://dl.min.io/server/minio/release/linux-arm64/archive/minio.RELEASE.2025-07-23T15-54-02Z"
        arm64.sha256 = "ec9f48fee97dee7e6ce8fe9f576471bcd52380c035091d8b075b64d606124c7e"

        [resources.sources.mc]
        extract = false
        in_subdir = false
        amd64.url = "https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2025-07-16T15-35-03Z"
        amd64.sha256 = "a5c3695b6f76ed958c0f099795f32091fced0d748ddc749c8b24e07681bbfbb9"
        arm64.url = "https://dl.min.io/client/mc/release/linux-arm64/archive/mc.RELEASE.2025-07-16T15-35-03Z"
        arm64.sha256 = "4d5f12adc96af56299893306f832cb49fd103cdd844a6a91a8e5de0592c74f5a"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.ports]
    main.default = 9000
    console.default = 9001
