packaging_format = 2

id = "minio"
name = "MinIO server"
description.en = "High Performance, Kubernetes Native Object Storage"
description.fr = "Serveur de stockage d'objets hautes performances"

version = "2023.09.07~ynh2"

maintainers = ["Raoul de Limezy"]

[upstream]
license = "AGPL-3.0-only"
website = "https://min.io"
admindoc = "https://docs.min.io/"
code = "https://github.com/minio/minio"
cpe = "cpe:2.3:a:minio:minio"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "150M"
ram.build = "700M"
ram.runtime = "700M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources]
        [resources.sources.minio]
        extract = false
        in_subdir = false

        arm64.url = "https://dl.min.io/server/minio/release/linux-arm64/archive/minio.RELEASE.2024-10-29T16-01-48Z"
        arm64.sha256 = "2458a9291be68a874400d1e1c0725eccc24fd55c8123b32c0416b09daa52210c"

        amd64.url = "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2024-10-29T16-01-48Z"
        amd64.sha256 = "b9513f863a6ec6141065c7357284973ee1cb54b16310c168371460297e82c448"

        [resources.sources.mc]
        extract = false
        in_subdir = false

        arm64.url = "https://dl.min.io/client/mc/release/linux-arm64/archive/mc.RELEASE.2024-10-29T15-34-59Z"
        arm64.sha256 = "a0312659c887da8e7f2427a7829bca34cdd29bd4c4af19bd7c4155156d00f543"

        amd64.url = "https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2024-10-29T15-34-59Z"
        amd64.sha256 = "a8a31621b4ad257583fb569fe31cfd72cf40e0b9b636971963c4815852c26914"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    main.default = 9000
    console.default = 36669
