packaging_format = 2

id = "minio"
name = "MinIO"
description.en = "High Performance, Kubernetes Native Object Storage"
description.fr = "Serveur de stockage d'objets hautes performances"

version = "2025.02.28~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://min.io"
admindoc = "https://docs.min.io/"
code = "https://github.com/minio/minio"
cpe = "cpe:2.3:a:minio:minio"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "150M"
ram.build = "700M"
ram.runtime = "700M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources]

        [resources.sources.minio]
        extract = false
        in_subdir = false
        amd64.url = "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2025-03-12T18-04-18Z"
        amd64.sha256 = "8ec42f70f5db7bfe584790b06af3f7e2b16f48488ea4c96e0ebd8cea40990dfa"
        arm64.url = "https://dl.min.io/server/minio/release/linux-arm64/archive/minio.RELEASE.2025-03-12T18-04-18Z"
        arm64.sha256 = "27c89f905e06aa1706bddb3c55d53dbbc550df8a44043cd77b36bc7ea66e156b"

        [resources.sources.mc]
        extract = false
        in_subdir = false
        amd64.url = "https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2025-02-15T10-36-16Z"
        amd64.sha256 = "7a03ba39e158708a9e88f1bf5c346c6651b15c784e4b2c7150b5b5f282f43c28"
        arm64.url = "https://dl.min.io/client/mc/release/linux-arm64/archive/mc.RELEASE.2025-02-15T10-36-16Z"
        arm64.sha256 = "4ad4e79e05153a6e8c3dae84e54a4bf16df403575f2a19cb7d688d6594e3d553"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.ports]
    main.default = 9000
    console.default = 9001
