#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --source_id="minio"
ynh_setup_source --dest_dir="$install_dir" --source_id="mc"

chmod +x "$install_dir/minio"
chmod +x "$install_dir/mc"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="High Performance Storage" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# SETUP MINIO CLIENT
#=================================================
ynh_script_progression "Configuring $app client..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app ./mc --autocompletion --no-color alias set minio "http://127.0.0.1:$port" "$admin" "$password" --api S3v4
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
