#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if ynh_app_upgrading_from_version_before_or_equal_to 2023.02.22~ynh1
then
	ynh_script_progression "Mirroring old Filesystem to secure MinIO start"
	tmp="/tmp/minio"
	mkdir "$tmp"
	chown -R $app:www-data "$tmp"
	pushd "$data_dir/"
		for d in * ; do
		if [ "$d" == "*" ]
		then
			ynh_script_progression "No buckets to migrate"
		else
			ynh_script_progression "Moving $d..."
			ynh_hide_warnings ynh_exec_as_app $install_dir/mc mirror --preserve "minio/$d" "$tmp/$d"
		fi
		done
		if ynh_compare_current_package_version --comparison eq --version 2022.09.01~ynh1
		then
			ynh_die "Sorry, your MinIO instance requires a complex manual migration. Please contact Limezy on the YunoHost forum"
		fi
		if ynh_compare_current_package_version --comparison eq --version 2022.11.11~ynh1
		then
			ynh_die "Sorry, your MinIO instance requires a complex manual migration. Please contact Limezy on the YunoHost forum"
		fi
		if ynh_compare_current_package_version --comparison eq --version 2023.01.11~ynh1
		then
			ynh_die "Sorry, your MinIO instance requires a complex manual migration. Please contact Limezy on the YunoHost forum"
		fi
	popd
    ynh_safe_rm "$data_dir"
	ynh_hide_warnings mkdir "$data_dir"
	chmod 750 "$data_dir"
	chmod -R o-rwx "$data_dir"
	chown -R $app:www-data "$data_dir"
else
	ynh_script_progression "No migration to be done"
fi

# Retrieve the password from the .env file
if [ -z "${password:-}" ]; then
	password=$(ynh_read_var_in_file --file="$install_dir/.env" --key="MINIO_ROOT_PASSWORD")
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --source_id="minio"
ynh_setup_source --dest_dir="$install_dir" --source_id="mc"

chmod +x "$install_dir/minio"
chmod +x "$install_dir/mc"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="High Performance Storage" --log="/var/log/$app/$app.log"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" #--wait_until="Console:"

#=================================================
# SETUP MINIO CLIENT
#=================================================
ynh_script_progression "Configuring$app client..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app ./mc --autocompletion --no-color alias set minio "http://127.0.0.1:$port" "$admin" "$password" --api S3v4
popd

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if ynh_app_upgrading_from_version_before_or_equal_to 2023.02.22~ynh1
then
	ynh_script_progression "Migration from Filesystem to Single-Node Single-Drive mode"
	pushd "$tmp/"
		for d in * ; do
		if [ "$d" == "*" ]
		then
			ynh_script_progression "No buckets to migrate"
		else
			ynh_script_progression "Migrating bucket $d"
				pushd $install_dir
					ynh_hide_warnings ynh_exec_as_app ./mc mb minio/"$d"
					ynh_hide_warnings ynh_exec_as_app ./mc mirror --preserve "$tmp/$d" "minio/$d"
					# This is a hack, but it will make outline_ynh users' lifes much easier !
					if [ "$d" == "outlinestorage" ]
					then
						ynh_hide_warnings ynh_exec_as_app ./mc anonymous set public minio/outlinestorage
					else
						ynh_script_progression "Bucket is migrated and objects are now mirrored. However, make sure to set properly access policy of bucket $d. That part of the migration can't be automated, sorry ! You can log into the minio console to perform your changes."
					fi
				popd
				ynh_safe_rm "DATA_$d"
		fi
		done
	popd
	ynh_safe_rm "$tmp"
else
	ynh_script_progression "No migration required"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
